server:
  servlet.context-path: /yinniedu
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/yinniedu?characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: yinniedu
    password: password
    tomcat:
      init-s-q-l: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jmx:
    default-domain: yinniedu

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

redis:
  database: 3
  host: 127.0.0.1
  port: 6379
  password: password
  timeout: 0

message:
  accessKeyId: xx
  accessKeySecret: xx
  connectTimeout: 1000
  readTimeout: 1000
  signName: xx
  templateCode: xx
  size: 5


filemanager:
  fileRootPath: /opt/edubusinessfile/
  urlRootPath: http://127.0.0.1:8080/yinniedu/file/readfile/

logging:
  file:
    name: /opt/javalog/yinniedu/pro.log

